### ISSUE TITLE
Servo GUI?

### ISSUE THREAD

**Issue by maxwell5** [servo/gleam#10]
Does this imply the Servo GUI will be OpenGL?
That'd be marvellous. Most "toolkits" are huge and bloated. OpenGL ES is the best alternative, I think. OpenGL coming right after it.

**Comment by kmcallister** [comment]
Servo is a browser engine that uses OpenGL to composite (and sometimes to render) content.  This is true whether that engine is embedded in an OpenGL app, a "native" UI toolkit app, or anything else.

Currently we have simple native-toolkit app shells for [Cocoa](https://github.com/pcwalton/miniservo-mac) and [GTK on Linux](https://github.com/pcwalton/miniservo-mac).  These are just for early testing; the UI story for a desktop browser based on Servo is as yet undecided.

**Comment by maxwell5** [comment]
> Currently we have simple native-toolkit app shells for Cocoa on OS X and GTK on Linux.

Any chances of a multi-platform OpenGL ES toolkit? It works on practically everything without unecessary overhead. Most of the toolkits like Qt, GTK, etc. are bloated.

**Comment by kmcallister** [comment]
Servo is an embeddable browser engine.  It won't be much work to set that up, whether or not it's the direction we go for our "official" GUI.

**Comment by kmcallister** [comment]
If you'd like to build a cross-platform OpenGL UI for Servo, [conrod](https://github.com/PistonDevelopers/conrod) seems like a nice way to go.
