### ISSUE TITLE
Add gl type detection function

### ISSUE THREAD

**Issue by sotaroikeda** [servo/gleam#104]
This issue is part of #99. To make runtime gl type selection works, we need to know current GL type is GL or GLES. It could help even when gl type is determined during build time.  I assume the function and enum is like the following. Is it OK for gleam?

#[derive(Debug, PartialEq)]
pub enum GlType {
    Gl,
    Gles,
}

#[cfg(not(target_os="android"))]
pub fn gl_type() -> GlType {
    GlType::Gl
}

#[cfg(target_os="android")]
pub fn gl_type() -> GlType {
    GlType::Gles
}

More background info could be in https://bugzilla.mozilla.org/show_bug.cgi?id=1325911

**Comment by kvark** [comment]
I think we can get away with having the full `GlType` image that has a `default()` constructor (implementing `Default` feature), which defaults to the platform GL (like it does now, but in compile time).
So,
```rust
#[derive(Debug, PartialEq)]
pub enum GlType {
  Gl,
  Gles,
}

impl Default for GlType {
  #[cfg(target_os="android")]
  fn default() -> GlType {
    GlType::Gles
  }
  #[cfg(not(target_os="android"))]
  fn default() -> GlType {
    GlType::Gl
  }
}
```
