### ISSUE TITLE
GL_OES_EGL_image_external support

### ISSUE THREAD

**Issue by JerryShih** [servo/gleam#117]
I'm trying to use a new target TEXTURE_EXTERNAL_OES in windows platform. It comes from gles. We use ANGLE gl context at windows platform. And the ANGLE is gles.
I'm not sure what I should do here. Should I just add that constant value im gleam?

The spec for this extension:
https://www.khronos.org/registry/OpenGL/extensions/OES/OES_EGL_image_external.txt

**Comment by JerryShih** [comment]
@glennw @kvark @emilio

**Comment by glennw** [comment]
Discussed in IRC but mentioned here for completeness:

If you add the extension here https://github.com/servo/gleam/blob/master/build.rs#L22 - it should generate the bindings for you.
