### ISSUE TITLE
get_integer_v/get_integer_64v/get_integer_iv/get_integer_64iv/get_boolean_v/get_float_v are memory unsafe

### ISSUE THREAD

**Issue by jdm** [servo/gleam#151]
They all provide a mutable pointer to a single value, but some parameters like GL_BLEND_COLOR are [specified](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glGet.xml) to write more than one value. This API implementation is wildly unsafe in its current form.

**Comment by nox** [comment]
I want to make all of them unsafe and let them take a `&mut [T]`, instead of trying to make everything memory-safe in gleam itself.
