### ISSUE TITLE
Rename viewport to set_viewport and get_viewport to viewport

### ISSUE THREAD

**Issue by nox** [servo/gleam#152]
…But let's wait to have a legit reason to make a breaking bump to do that.

**Comment by jdm** [comment]
The names of the public APIs in this crate mirror the names of the GL APIs they wrap, since this is a quite low-level GL binding library. I'm not sure that we should break that pattern for just this particular case.

**Comment by nox** [comment]
Closing this because Josh Is Right(tm).
