### ISSUE TITLE
Please make a version break every time you add functions to the `Gl` trait

### ISSUE THREAD

**Issue by fschutt** [servo/gleam#200]
I've now gotten this error here: https://github.com/maps4print/azul/issues/203#issuecomment-526901138 - which happens because I have a custom implementation of the `Gl` trait for providing a "virtual" OpenGL driver for unit-testing purposes. gleam 0.6.20 added three new functions; `gen_vertex_arrays_apple`, `delete_vertex_arrays_apple`, `bind_vertex_array_apple`. You can close this issue if you've read it, but I just wanted to say it - cargo relies on semantic versioning to be done properly and this is at least the fifth time that my code breaks because some dependency didn't stick to semver. Sadly, I'm not able to lock down the version of gleam for a library if gleam doesn't adhere to semver, because cargo ignores Cargo.lock files of libraries. While this is more of a problem with cargo, for the meantime it would be nice to not release new versions of gleam under 0.6 if they aren't actually compatible with the old `Gl` trait.

**Comment by jdm** [comment]
Whoops. Apologies for the semantically-invalid version.

**Comment by nox** [comment]
Let's yank 0.6.20 and release 0.7.

**Comment by jdm** [comment]
Yanked.
