### ISSUE TITLE
3D textures disabled on Android

### ISSUE THREAD

**Issue by kvark** [servo/gleam#92]
```rust
#[cfg(not(target_os="android"))]
pub fn tex_image_3d(target: GLenum,
...
#[cfg(not(target_os="android"))]
pub fn copy_tex_sub_image_3d(target: GLenum,
...
```

They are [supported](http://docs.gl/es3/glTexImage3D) on GLES 3.0, so I believe `gleam` should be exposing them on Android.

related - https://github.com/servo/webrender/issues/487

**Comment by larsbergstrom** [comment]
@glennw Does this sound reasonable to you? This is currently blocking Servo on Android.

**Comment by glennw** [comment]
Yes, gleam should expose them on android. This is just from a long time ago when we only exposed es2 on android and can be removed now.

**Comment by mmatyas** [comment]
Could someone bump the version number, please?

**Comment by larsbergstrom** [comment]
Bumped and published!
